plugins:
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme

title: 🧩 Open Research Platforms

author:
  name: 'Casey Gollan'
  email: 'hello@caseyagollan.com'

description: >- # this means to ignore newlines until "baseurl:"

permalink: pretty

collections:
  platforms:
    output: true
    permalink: /:name/

defaults:
  -
    scope:
      path: ""
      type: "platforms" # a collection in your site, in plural form
    values:
      layout: platform

bootstrap:
  social_links:
    twitter: 'https://twitter.com/@caseyg'
    linkedin: 'https://linkedin.com/in/casey-gollan'
  header_pages:
   - index.md
   - criteria.md
   - why.md